project_id = "iuzpdjplasndyvbzhlzd"

[functions.scrape-polymarket]
verify_jwt = false

[functions.polymarket-realtime]
verify_jwt = false

[functions.chainlink-price-collector]
verify_jwt = false

[functions.get-market-tokens]
verify_jwt = false

[functions.rtds-proxy]
verify_jwt = false

[functions.clob-proxy]
verify_jwt = false

[functions.clob-prices]
verify_jwt = false

[functions.save-expired-market]
verify_jwt = false
